"""add exercises table with muscle contributions

Revision ID: 59779afa0396
Revises: 2cc58ca97800
Create Date: 2025-11-22 20:20:39.734237+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59779afa0396'
down_revision: Union[str, None] = '2cc58ca97800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('name', sa.String(length=200), nullable=False, comment="Exercise name (e.g., 'Barbell Bench Press')"),
    sa.Column('description', sa.Text(), nullable=False, comment='Exercise description and instructions'),
    sa.Column('equipment', sa.String(length=50), nullable=False, comment='Equipment type enum value (BARBELL, DUMBBELL, etc.)'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL to exercise demonstration image or video'),
    sa.Column('is_global', sa.Boolean(), nullable=False, comment='True if admin-created exercise available to all organizations'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True, comment='User who created the exercise (None for global exercises)'),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='Organization that owns the exercise (None for global exercises)'),
    sa.Column('muscle_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Mapping of muscle groups to volume contribution levels (0.25, 0.5, 0.75, 1.0)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Resistance training exercises with muscle targeting and volume contributions'
    )
    op.create_index(op.f('ix_exercises_created_by_user_id'), 'exercises', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_is_global'), 'exercises', ['is_global'], unique=False)
    op.create_index('ix_exercises_muscle_contributions', 'exercises', ['muscle_contributions'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index('ix_exercises_name_global_unique', 'exercises', ['name'], unique=True, postgresql_where=sa.text('is_global = true'))
    op.create_index('ix_exercises_name_org_unique', 'exercises', ['name', 'organization_id'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_index('ix_exercises_org_global', 'exercises', ['organization_id', 'is_global'], unique=False, postgresql_where=sa.text('is_global = false'))
    op.create_index(op.f('ix_exercises_organization_id'), 'exercises', ['organization_id'], unique=False)
    op.create_index('ix_exercises_search', 'exercises', [sa.literal_column("to_tsvector('english', name || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('organizations_lemonsqueezy_customer_id_key'), 'organizations', type_='unique')
    op.drop_constraint(op.f('organizations_lemonsqueezy_subscription_id_key'), 'organizations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('organizations_lemonsqueezy_subscription_id_key'), 'organizations', ['lemonsqueezy_subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('organizations_lemonsqueezy_customer_id_key'), 'organizations', ['lemonsqueezy_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_exercises_search', table_name='exercises', postgresql_using='gin')
    op.drop_index(op.f('ix_exercises_organization_id'), table_name='exercises')
    op.drop_index('ix_exercises_org_global', table_name='exercises', postgresql_where=sa.text('is_global = false'))
    op.drop_index('ix_exercises_name_org_unique', table_name='exercises', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('ix_exercises_name_global_unique', table_name='exercises', postgresql_where=sa.text('is_global = true'))
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index('ix_exercises_muscle_contributions', table_name='exercises', postgresql_using='gin')
    op.drop_index(op.f('ix_exercises_is_global'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_by_user_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
